- name: initialize the cluster (this could take some time)
  shell: kubeadm init --control-plane-endpoint "{{ item }}" --upload-certs --pod-network-cidr=10.244.0.0/16 --skip-phases addon/kube-proxy >> cluster_initialized.log
  args:
    chdir: /tmp
    creates: cluster_initialized.log
  with_items:
    - "{{ k8s_ipv }}"

- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name:  Copy admin.conf to Kubernetes configuration directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root

- name: Generate Kubernetes join token
  shell: kubeadm token create --print-join-command
  register: kubernetes_join_command

- name: Save Kubernetes join command to local file
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="join/kubernetes_join_command" mode=0777

- name: Generate control-plane certificate key token
  shell: kubeadm init phase upload-certs --upload-certs
  register: kubernetes_master_token

- name: Save control-plane certificate token to local file
  local_action: copy content="{{ kubernetes_master_token.stdout_lines[2] }}" dest="join/kubernetes_master_token" mode=0777
